# Change these first
owner: bondarewicz # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: www
    url: https://bondarewicz.com
  - name: api
    url: https://api.bondarewicz.com/v1/version

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  cname: status.bondarewicz.com
  logoUrl: ""
  name: status.bondarewicz.com
  introTitle: ""
  introMessage: 
  navbar:
    - title: status
      href: https://github.com/$OWNER/$REPO
    - title: www
      href: https://github.com/$OWNER/com
    - title: api
      href: https://github.com/$OWNER/api

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
